import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "@/components/ui/sonner";
import Providers from "@/components/Providers";
import { AppSidebar } from "@/components/AppSidebar";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { LinkType } from "@/types";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await getServerSession(authOptions);
  const user = session?.user;

  const links: LinkType[] = [
    { label: "Dashboard", href: "/dashboard", iconKey: "dashboard" },
    { label: "Profile", href: "/profile", iconKey: "profile" },
    { label: "Settings", href: "/settings", iconKey: "settings" },
    { label: "Logout", href: "/api/auth/signout", iconKey: "logout" },
  ];
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="dark">
        <Providers>
            <div className="flex min-h-screen w-full">
              {/* Sidebar */}
              {user ? (
                <AppSidebar
                  links={links}
                  user={{ name: user.name ?? "User", avatar: user.image ?? "/default-avatar.png" }}
                />
              ) : (
                <div className="w-64 p-4">Please log in</div> // Placeholder for unauthenticated users
              )}
              {/* Main content */}
              <main className="flex-1 p-4">{children}</main>
            </div>
          </Providers>
        </ThemeProvider>
        <Toaster />
      </body>
    </html>
  );
}
